version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y zip

  build:
    commands:
      - pip install --ignore-installed -r requirements.txt -t ./src 
      - cd src
      - zip -r ../eclass_for_alexa.zip . &>/dev/null

artifacts:
  files:
    - *.zip
  discard-paths: yes
