version: 0.1

phases:
  build:
    commands:
      - apt-get update
      - apt-get install zip
      - pip install --ignore-installed -r requirements.txt -t ./src 
      - cd src
      - mkdir -p ../artifacts
      - zip -r ../artifacts/eclass_for_alexa.zip .

artifacts:
  files:
    - artifacts/eclass_for_alexa.zip
