version: 0.1

phases:
  build:
    commands:
      - apt-get update -y
      - apt-get install -y zip
      - pip install --ignore-installed -r requirements.txt -t ./src 
      - cd src
      - mkdir -p ../artifacts
      - zip -r ../artifacts/eclass_for_alexa.zip . &>/dev/null
      - ls /tmp

artifacts:
  files:
    - artifacts/*.zip
  discard-paths: yes
